### ISSUE TITLE
EXISTWHITELIST is missed

### ISSUE THREAD

**Issue by Karen09** [thbe/puppet-rkhunter#5]
when you run  
[root@rkhunter ~]#  rkhunter --propupd
Invalid SCRIPTWHITELIST configuration option: Non-existent pathname: /usr/bin/whatis
so what its mean ` 
[root@rkhunter ~]# cat /etc/rkhunter.conf | grep EXISTWHITELIST
#EXISTWHITELIST=""
---------------------------------------------------------------------------------------
solving is vi /etc/rkhunter.conf 
remove #  at #EXISTWHITELIST=""
add PATH /usr/bin/whatis

so it must looks like 
[root@rkhunter ~]# cat /etc/rkhunter.conf | grep EXISTWHITELIST
EXISTWHITELIST="/usr/bin/whatis"

but it is manual steps, which we would not like ,please solve it in dev level ,en notify me when its done )
greetz

**Comment by thbe** [comment]
Hi Karen, I've added the merge request. I will upload an extended version later today with updated rkhunter.conf (compared to the actual rpm version) and also an additional check for SAPDB.

**Comment by Karen09** [comment]
Hi
will checkout new updates )
Greetz

**Comment by thbe** [comment]
Pushed to forge right now ;)

**Comment by Karen09** [comment]
seems much proper and worked for me perfectly.
thanks.

**Comment by Karen09** [comment]
can you check something for me please 
class { '::rkhunter':
  rootEmail => 'john.doe@example.local',
}
then i must find it back at /etc/rkhunter.conf  
https://github.com/thbe/puppet-rkhunter/blob/master/templates/etc/rkhunter.conf.erb#L137
here? 

one more thing when i put in hiera ::rkhunter::rootEmail:: foo@mail.com

and in` modules/profiles/manifests/rkhunter.pp 
Class profiles::rkhunter {
   include ::rkhunter
}
i did not get the same if i will do 
class { '::rkhunter':
  rootEmail => 'foo@mail.com',
}

thanks for collaborate .

**Comment by thbe** [comment]
Hi Karen,

nope, you won't find it in rkhunter.conf. The mail on warning entry
generate a second mail containing something like "there might be a problem
on this host". Additionally you get a second mail telling you what rkhunter
is complaining. I don't need the warning mail, so this feature is disabled
in my module. I only want the mail that tells me what is wrong or at least
what rkhunter thinks that is wrong. The email address here is controlled by
/etc/sysconfig/rkhunter file.

Regards Thomas

2015-02-20 16:48 GMT+01:00 Karen <notifications@github.com>:

> can you check something for me please
> class { '::rkhunter':
> rootEmail => 'john.doe@example.local',
> }
> then i must find it back at /etc/rkhunter.conf
>
>
> https://github.com/thbe/puppet-rkhunter/blob/master/templates/etc/rkhunter.conf.erb#L137
> here?
>
> one more thing when i put in hiera ::rkhunter::rootEmail:: foo@mail.com
>
> and in` modules/profiles/manifests/rkhunter.pp
> Class profiles::rkhunter {
> include ::rkhunter
> }
> i did not get the same if i will do
> class { '::rkhunter':
> rootEmail => 'foo@mail.com',
> }
>
> thanks for collaborate .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thbe/puppet-rkhunter/issues/5#issuecomment-75259645>.
>



-- 
Linux ... enjoy the ride!

**Comment by Karen09** [comment]
Thanks Thomas 
its really help to figure out about mail stuff. 
Greetings Karen

**Comment by Karen09** [comment]
hi THOMAS
one more question about puppet "include" please explain what i miss take .
  class { '::rkhunter':
    rootEmail    => 'localhost',#"${root_email}",
    remoteSyslog => true,
  }

normally that is the same if i do
include '::rkhunter' 

and in hiera.yaml 
::rkhunter::rootEmail: localhost
::rkhunter::remoteSyslog: true 
Greetz Karen

**Comment by thbe** [comment]
Hi Karen,

it's not completely the same, but more or less. The include pattern with
hiera didn't work if you use ENC for the node definition. I use in my
environment currently Foreman as an ENC for Puppet, so the include pattern
didn't work for me. But if you use hiera, it will work for you.

Regards Thomas

2015-02-23 13:33 GMT+01:00 Karen <notifications@github.com>:

> hi THOMAS
> one more question about puppet "include" please explain what i miss take .
> class { '::rkhunter':
> rootEmail => 'localhost',#"${root_email}",
> remoteSyslog => true,
> }
>
> normally that is the same if i do
> include '::rkhunter'
>
> and in hiera.yaml
> ::rkhunter::rootEmail: localhost
> ::rkhunter::remoteSyslog: true
> Greetz Karen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thbe/puppet-rkhunter/issues/5#issuecomment-75533653>.
>



-- 
Linux ... enjoy the ride!

**Comment by Karen09** [comment]
One more time Thank you for help .
Greetings Karen
